## Question_4_Solution:

**Q-4.** Imagine you working as a sale manager now you need to predict the Revenue
and whether that particular revenue is on the weekend or not and find the
Informational_Duration using the Ensemble learning algorithm
Dataset This is the Dataset You can use this dataset for this question.

In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
# online_shoppers_intention dataset:
df = pd .read_csv('useful/Q4.csv')
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [4]:
# getting min-max values from each column
for column in df.columns:
    min_value = df[column].min()  # Get the minimum value for the column
    max_value = df[column].max()  # Get the maximum value for the column
    print(f"Column '{column}':")
    print(f"Min Value: {min_value}")
    print(f"Max Value: {max_value}")
    print()

Column 'Administrative':
Min Value: 0
Max Value: 27

Column 'Administrative_Duration':
Min Value: 0.0
Max Value: 3398.75

Column 'Informational':
Min Value: 0
Max Value: 24

Column 'Informational_Duration':
Min Value: 0.0
Max Value: 2549.375

Column 'ProductRelated':
Min Value: 0
Max Value: 705

Column 'ProductRelated_Duration':
Min Value: 0.0
Max Value: 63973.52223

Column 'BounceRates':
Min Value: 0.0
Max Value: 0.2

Column 'ExitRates':
Min Value: 0.0
Max Value: 0.2

Column 'PageValues':
Min Value: 0.0
Max Value: 361.7637419

Column 'SpecialDay':
Min Value: 0.0
Max Value: 1.0

Column 'Month':
Min Value: Aug
Max Value: Sep

Column 'OperatingSystems':
Min Value: 1
Max Value: 8

Column 'Browser':
Min Value: 1
Max Value: 13

Column 'Region':
Min Value: 1
Max Value: 9

Column 'TrafficType':
Min Value: 1
Max Value: 20

Column 'VisitorType':
Min Value: New_Visitor
Max Value: Returning_Visitor

Column 'Weekend':
Min Value: False
Max Value: True

Column 'Revenue':
Min Value: False
Max Value: True

Column Descriptions:

Administrative: This is the number of pages of this type (administrative) that the user visited.

Administrative_Duration: This is the amount of time spent in this category of pages.

Informational: This is the number of pages of this type (informational) that the user visited.

Informational_Duration: This is the amount of time spent in this category of pages.

ProductRelated: This is the number of pages of this type (product related) that the user visited.

ProductRelated_Duration: This is the amount of time spent in this category of pages.

BounceRates: The percentage of visitors who enter the website through that page and exit without triggering any additional tasks.

ExitRates: The percentage of pageviews on the website that end at that specific page.

PageValues: The average value of the page averaged over the value of the target page and/or the completion of an eCommerce transaction.
More information about how this is calculated

SpecialDay: This value represents the closeness of the browsing date to special days or holidays (eg Mother's Day or Valentine's day) in which the transaction is more likely to be finalized. More information about how this value is calculated below.

Month: Contains the month the pageview occurred, in string form.

OperatingSystems: An integer value representing the operating system that the user was on when viewing the page.

Browser: An integer value representing the browser that the user was using to view the page.

Region: An integer value representing which region the user is located in.

TrafficType: An integer value representing what type of traffic the user is categorized into.
Read more about traffic types here.

VisitorType: A string representing whether a visitor is New Visitor, Returning Visitor, or Other.

Weekend: A boolean representing whether the session is on a weekend.

Revenue: A boolean representing whether or not the user completed the purchase.

In [5]:
df.shape

(12330, 18)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [7]:
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [8]:
df['Month'].unique()

array(['Feb', 'Mar', 'May', 'Oct', 'June', 'Jul', 'Aug', 'Nov', 'Sep',
       'Dec'], dtype=object)

In [9]:
df['VisitorType'].unique()

array(['Returning_Visitor', 'New_Visitor', 'Other'], dtype=object)

In [10]:
# Manual encoding for 'Month' column
month_mapping = {'Feb': 2, 'Mar': 3, 'May': 5, 'June': 6,
                 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}
df['Month'] = df['Month'].map(month_mapping)

# Manual encoding for 'VisitorType' column
visitor_mapping = {'New_Visitor': 0, 'Returning_Visitor': 1, 'Other': 2}
df['VisitorType'] = df['VisitorType'].map(visitor_mapping)

In [11]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,1,1,1,1,1,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,2,1,2,1,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,4,1,9,3,1,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,2,3,2,2,4,1,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,2,3,3,1,4,1,True,False

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  int64
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  int64
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(9)
memory usage: 1.5 MB

In [13]:
# Split the data into features (X) and target variable (y)
X = df.drop(['Revenue'], axis=1)
y = df['Revenue']

In [14]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest Classifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy*100, '%')

Model Accuracy: 88.88888888888889 %

In [19]:
# Predict the revenue and weekend for a new data instance
new_data = pd.DataFrame({
    'Administrative': [5],
    'Administrative_Duration': [250],
    'Informational': [2],
    'Informational_Duration': [100],
    'ProductRelated': [10],
    'ProductRelated_Duration': [500],
    'BounceRates': [0.05],
    'ExitRates': [0.1],
    'PageValues': [15],
    'SpecialDay': [0.2],
    'Month': ['May'],
    'OperatingSystems': [2],
    'Browser': [4],
    'Region': [1],
    'TrafficType': [4],
    'VisitorType': ['Returning_Visitor'],
    'Weekend': [1]
})

In [20]:
# Manual encoding for 'Month' column in the new data
new_data['Month'] = new_data['Month'].map(month_mapping)

# Manual encoding for 'VisitorType' column in the new data
new_data['VisitorType'] = new_data['VisitorType'].map(visitor_mapping)

In [21]:
revenue_pred = model.predict(new_data)[0]

if revenue_pred == True and new_data['Weekend'][0] == 1:
    print('Yes, Revenue Generation on Weekend.')
else:
    print('No Revenue Generation on Weekend.')

No Revenue Generation on Weekend.

In [22]:
informational_duration_pred = new_data['Informational_Duration'][0]

print("Informational_Duration: =>", 'Time spent to in a specific category of ITEMS: ', informational_duration_pred/100, 'Minutes')

Informational_Duration: => Time spent to in a specific category of ITEMS:  1.0 Minutes